package utils;

public final class Constants {
    public static String ENVIRONMENT_STATE_REQUEST_CONVERSATION_ID = "ENVIRONMENT_STATE_REQUEST_CONVERSATION_ID";
    public static String ENVIRONMENT_STATE_NOTIFICATION_CONVERSATION_ID = "ENVIRONMENT_STATE_NOTIFICATION_CONVERSATION_ID";
    public static String ENVIRONMENT_ACTION_CONVERSATION_ID = "ENVIRONMENT_ACTION_CONVERSATION_ID";
    public static String ENVIRONMENT_AGENT_TYPE = "ENVIRONMENT_AGENT";
    public static String NAVIGATOR_AGENT_TYPE = "NAVIGATOR_AGENT";
    public static String SPELEOLOGIST_AGENT_TYPE = "SPELEOLOGIST_AGENT";
}